# --- PYTHON AI MICROSERVICE ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remvault-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
      containers:
      - name: ai-service
        image: remvault-ai-image:latest
        imagePullPolicy: Never # Forces k8s to use your locally built image
        env:
        - name: REDIS_HOST
          value: remvault-cache
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: remvault-ai
spec:
  selector:
    app: ai
  ports:
  - port: 8000
  - targetPort: 8000

# --- KTOR CORE MONOLITH ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remvault-core
spec:
  replicas: 1 # You could change this to 3 to simulate high-availability!
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
      - name: core-app
        image: remvault-core-image:latest
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          value: remvault-db
        - name: REDIS_HOST
          value: remvault-cache.default.svc.cluster.local
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: remvault-core
spec:
  type: NodePort # Exposes this service to the outside world
  selector:
    app: core
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080 # This means you'll access Ktor at http://<minikube-ip>:30080