# --- REDIS CACHE ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remvault-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: remvault-cache
spec:
  selector:
    app: cache
  ports:
  - port: 6379

# --- POSTGRES STORAGE CLAIM ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# --- POSTGRES DATABASE ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remvault-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: remvault
        - name: POSTGRES_PASSWORD
          value: remvault
        - name: POSTGRES_DB
          value: remvault
        ports:
        - containerPort: 5432
        # 1. Mount the volume inside the container
        volumeMounts:
        - name: pgdata-storage
          mountPath: /var/lib/postgresql/data
      # 2. Tell the pod to use the PVC we created above
      volumes:
      - name: pgdata-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: remvault-db
spec:
  selector:
    app: database
  ports:
  - port: 5432